# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-{{ .Environment.CIRCLE_JOB }}-dependencies-{{ checksum "yarn.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-{{ .Environment.CIRCLE_JOB }}-dependencies-

    - run: yarn install

    - save_cache:
        paths:
          - node_modules
        key: v1-{{ .Environment.CIRCLE_JOB }}-dependencies-{{ checksum "yarn.lock" }}

    # run lint!
    - run: yarn lint

    # run tests!
    - run: yarn test

jobs:
  node-lts:
    <<: *defaults
    docker:
      - image: circleci/node:10

  node-current:
    <<: *defaults
    docker:
      - image: circleci/node:11

# Workflow definition
workflows:
  version: 2
  test:
    jobs:
      - node-lts
      - node-current
