name: Github Action CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nuxt/actions-yarn@master
        with:
          cmd: install
      - uses: nuxt/actions-yarn@master
        with:
          cmd: test
      - uses: nuxt/actions-yarn@master
        with:
          cmd: audit
